### PR TITLE
Refactored & tested

### PR DESCRIPTION
**Pull request by AlexMoroz**

### CODE REVIEW

**Comment by missxa** [comment]
ehm why is this not in the release? @Waguramu

**Comment by Waguramu** [comment]
Lucas said he found some bugs, which he couldn't fix yet. So I have released the version which is fine. This one we will try fixing and releasing until Wednesday

**Comment by Waguramu** [comment]
Lucas said he found some bugs, which he couldn't fix yet. So I have released the version which is fine. This one we will try fixing and releasing until Wednesday

**Comment by AlexMoroz** [comment]
I've also said that I fixed that bugs.

**Comment by Waguramu** [comment]
Last bugs with GET and REMOVE fixed, @missxa could you merge?

**Pull request merged**
